package com.igate.iconnect.constants;

public class COMMON_Email_ApprovalConstants {
	
	public final static  String IC_APPROVAL_DETAILS_VALIADTION="declare @Ticket int = ?,"
			+ " @Approver varchar(20) = ?;"
+ " if not exists (select 1 from IC_IHD_TICKET_DETAILS where TICKET_ID = @Ticket)"
+ " begin"
+ " select 'Invalid Ticket' 'Check'"
+ " end"
+ " else"
+ " if not exists (select 1 from IC_MAIL_SENDER_DETAIL ap"
+ " inner join IC_WORKFLOW_TRANSITION_MASTER tra on tra.TRANSITION_ID = ap.TRANSITION_ID"
+ " inner  join IC_IHD_TICKET_DETAILS tick on tick.WORKFLOW_STATE = tra.TO_STATE and tick.TICKET_ID = @Ticket"
+ " where ap.IS_APPROVAL_REQUIRED = 1)"
+ " begin"
+ " select 'Not waiting for approval' 'Check'"
+ " end"
+ " else"
+ " begin"
+ " select" 
+ " case when" 
+ " case when mgr.EMPLOYEE_ID is NULL then usr.REPORTING_MANAGER  else mgr.EMPLOYEE_ID end = @Approver"
+ " then 'Valid' else 'Approver Invalid' end 'Check'"
+ " from IC_IHD_TICKET_DETAILS tick"
+ " inner join IC_WORKFLOW_STATE_MASTER wsm on wsm.STATE_ID = tick.WORKFLOW_STATE" 
 + " and wsm.NAME like 'Waiting For RO Approval'"
+ " inner join IC_USER_DETAILS usr on usr.EMPLOYEE_ID = tick.REQUESTED_BY and usr.IS_ACTIVE = 1"
       + " left outer join IC_USER_DETAILS mgr on mgr.EMPLOYEE_ID = tick.MANAGER_ID and mgr.IS_ACTIVE = 1"
+ " where tick.TICKET_ID = @Ticket"
+ " union"
+ " select" 
+ " case when  exists (select 1 from IC_IHD_APPROVER_EMPLOYEE_DETAILS where EMPLOYEE_ID = @Approver and APPROVER_ID = 4 and IS_ACTIVE = 1)"
+ " then 'Valid' else 'Approver Invalid' end 'Check'"
+ " from IC_IHD_TICKET_DETAILS tick"
+ " inner join IC_WORKFLOW_STATE_MASTER wsm on wsm.STATE_ID = tick.WORKFLOW_STATE" 
 + " and wsm.NAME like 'Waiting For IS-Head Approval'"
+ " where tick.TICKET_ID = @Ticket"
+ " union"
+ " select" 
+ " case when  exists (select 1 from IC_IHD_APPROVER_EMPLOYEE_DETAILS where EMPLOYEE_ID = @Approver and APPROVER_ID = 2 and IS_ACTIVE = 1)"
+ " then 'Valid' else 'Approver Invalid' end 'Check'"
+ " from IC_IHD_TICKET_DETAILS tick"
+ " inner join IC_WORKFLOW_STATE_MASTER wsm on wsm.STATE_ID = tick.WORKFLOW_STATE" 
 + " and wsm.NAME like 'Waiting For IT Function Head Approval'"
+ " where tick.TICKET_ID = @Ticket"
+ " union"
+ " select" 
+ " case when  exists (select 1 from IC_IHD_APPROVER_EMPLOYEE_DETAILS where EMPLOYEE_ID = @Approver and APPROVER_ID = 3 and IS_ACTIVE = 1)"
+ " then 'Valid' else 'Approver Invalid' end 'Check'"
+ " from IC_IHD_TICKET_DETAILS tick"
+ " inner join IC_WORKFLOW_STATE_MASTER wsm on wsm.STATE_ID = tick.WORKFLOW_STATE" 
 + " and wsm.NAME like 'Waiting For Infosec Approval'"
+ " where tick.TICKET_ID = @Ticket"
+ " union"
+ " select" 
+ " case when  exists (select 1 from IC_IHD_APPROVER_EMPLOYEE_DETAILS where EMPLOYEE_ID = @Approver and APPROVER_ID = 6 and IS_ACTIVE = 1)"
+ " then 'Valid' else 'Approver Invalid' end 'Check'"
+ " from IC_IHD_TICKET_DETAILS tick"
+ " inner join IC_WORKFLOW_STATE_MASTER wsm on wsm.STATE_ID = tick.WORKFLOW_STATE" 
 + " and wsm.NAME like 'Waiting For SLM Approval'"
+ " where tick.TICKET_ID = @Ticket"
+ " union"
+ " select" 
+ " case when  tick.MANAGER_ID = @Approver"
+ " then 'Valid' else 'Approver Invalid' end 'Check'"
+ " from IC_IHD_TICKET_DETAILS tick"
+ " inner join IC_WORKFLOW_STATE_MASTER wsm on wsm.STATE_ID = tick.WORKFLOW_STATE" 
 + " and wsm.NAME like 'Sent For Approval'"
+ " where tick.TICKET_ID = @Ticket"
+ " end";
	
	public final static  String IC_TICKET_DETAILS="select tic.TICKET_ID,tic.FUNCTION_ID,tic.PRIORITY_ID,tic.SUB_CATEGORY_ID,tic.LOCATION_ID,tic.LOC_DET_ID,wsm.NAME 'WORKFLOW_STATE',cm.NAME 'FUNCTION'," 
			+ " (select EMAIL_ADDRESS from IC_USER_DETAILS where EMPLOYEE_ID=?) 'EMAIL_ADDRESS'"
			+ " from IC_IHD_TICKET_DETAILS tic"
	+ " join IC_WORKFLOW_STATE_MASTER wsm on wsm.STATE_ID=tic.WORKFLOW_STATE"
	+ " join IC_IHD_CATEGORY_MASTER cm on cm.CATEGORY_ID=tic.FUNCTION_ID"
	+ " where tic.TICKET_ID=?";
	public final static  String TCR_APPROVAL_DETAILS_VALIADTION="declare @Ticket int = ?,"
			+ " @Approver varchar(20) = ?;"
+ " if not exists (select 1 from IC_TCR_TICKET_DETAILS where ISSUE_ID = @Ticket)"
+ " begin"
+ " select 'Invalid Ticket' 'Check'"
+ " end"
+ " else"
+ " if not exists (select 1 from IC_TCR_TICKET_DETAILS TTD"
+ " join IC_WORKFLOW_STATE_MASTER iwsm on ttd.WORKFLOW_STATE=iwsm.STATE_ID and iwsm.WORKFLOW_ID=3"
+ " where (iwsm.NAME='Sent For Approval' or iwsm.NAME='Sent for Infosec Approval') and TTD.ISSUE_ID=@Ticket)"
+ " begin"
+ " select 'Not waiting for approval' 'Check'"
+ " end"
+ " else"
+ " if  exists (select 1 from "
+ " IC_TCR_TICKET_DETAILS TTD "
+ " JOIN IC_TCR_TICKET_APPROVAL_DETAILS TTAD ON TTAD.ISSUE_ID=TTD.ISSUE_ID"
+ " JOIN IC_TCR_APPROVER_MASTER TAM ON  TAM.APPROVER_ID=TTAD.APPROVER_ID"
+ " WHERE TTD.ISSUE_ID=@Ticket AND TAM.EMPLOYEE_ID=@Approver and TAM.IS_ACTIVE=1 )"
+ " begin"
+ " select 'Valid' 'Check'"
+ " end"
+ " else"
+ " begin"
+ " select 'Approver Invalid' 'Check'"
+ " end";
	
	public final static  String TCR_TICKET_DETAILS="select ttd.ISSUE_ID,TGM.NAME 'GROUP',iwsm.NAME 'WORKFLOW_STATE',(select EMAIL_ADDRESS from IC_USER_DETAILS where EMPLOYEE_ID=?) 'EMAIL_ADDRESS' from IC_TCR_TICKET_DETAILS ttd "
			+ " join IC_TCR_GROUP_MASTER TGM on TGM.GROUP_ID=ttd.GROUP_ID"
+ " join IC_WORKFLOW_STATE_MASTER iwsm on iwsm.STATE_ID=ttd.WORKFLOW_STATE"
+ " where ISSUE_ID=?";
	
	public final static  String SENDER_EMAILADDRESS="select EMAIL_ADDRESS from IC_USER_DETAILS where EMPLOYEE_ID=?";
	

}
