package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.igate.iconnect.BO.User;
import com.igate.iconnect.util.SessionListener;
import com.igate.iconnect.BO.COMMON_Menu;
import com.igate.iconnect.BO.WORKFLOW_Role;
import com.igate.iconnect.BO.User;
import java.util.List;

public final class MainLayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(5);
    _jspx_dependants.add("/WEB-INF/view/UNIVERSAL_Header.jsp");
    _jspx_dependants.add("/WEB-INF/view/UNIVERSAL_WestPanel.jsp");
    _jspx_dependants.add("/WEB-INF/view/UNIVERSAL_EastPanel.jsp");
    _jspx_dependants.add("/WEB-INF/view/UNIVERSAL_CenterPanel.jsp");
    _jspx_dependants.add("/WEB-INF/view/UNIVERSAL_Footer.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id=request.getParameter("id");
String loginUsers = (String)request.getSession().getAttribute("userLoginId");
User userOb = (User) request.getSession().getAttribute(loginUsers);

String empNames = userOb.getUserName();
String roles = (String)userOb.getUserRole();
String roleId=(String)userOb.getUserRoleId();
String subjects=request.getParameter("subject");
String categorys=request.getParameter("category");
String subcategorys=request.getParameter("subcategory");
String functions=request.getParameter("function");
String todoActions=request.getParameter("toDOAction");// To Know whether the user clicked on View or Edit.
SessionListener counter = (SessionListener) session.getAttribute("counter");

      out.write('\r');
      out.write('\n');
 String jsDirPath = (String)getServletContext().getInitParameter("jsDirPath");  
   String cssDirPath = (String)getServletContext().getInitParameter("cssDirPath"); 

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<title>IConnect : Unified Service Desk for Life & Health</title>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(cssDirPath);
      out.write("/jquery-ui.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(cssDirPath);
      out.write("/jquery.treeview.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(cssDirPath);
      out.write("/layout-default-latest.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"  href=\"");
      out.print(cssDirPath);
      out.write("/iconnect.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"  href=\"");
      out.print(cssDirPath);
      out.write("/jbar_style.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(cssDirPath);
      out.write("/user.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(cssDirPath);
      out.write("/colorbox.css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body onunload=\"ticketUnlocking()\">\r\n");
      out.write("\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/block.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/ddaccordion.js\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/ui.core.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/ui.accordion.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/effects.core.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.layout-latest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/ui.tabs.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.cookie.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.treeview.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/demo.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/debug.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/json.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/requiredfunctions.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/custom/ADMIN_WorkFlow.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/custom/UNIVERSAL_Header.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.bar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/UNIVERSAL_Security.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.colorbox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.blockUI.js\"></script>  \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("if(top.location.href.substring(0, top.location.href.lastIndexOf(\"/\")+1)!=window.location.href.substring(0, window.location.href.lastIndexOf(\"/\")+1)){\r\n");
      out.write("\ttop.location=window.location;\r\n");
      out.write("}\r\n");
      out.write("var accOpts_searchWindow = {\r\n");
      out.write("\t\t  autoHeight: false,\r\n");
      out.write("\t\t  collapsible: true,\r\n");
      out.write("\t\t  alwaysOpen: false,\r\n");
      out.write("\t\t  active: false\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t};\r\n");
      out.write("var accOpts_serviceWindow = {\r\n");
      out.write("\t\t  autoHeight: false,\r\n");
      out.write("\t\t  collapsible: true,\r\n");
      out.write("\t\t  alwaysOpen: false, \r\n");
      out.write("\t\t  active: false\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t};\r\n");
      out.write("var roleIde=");
      out.print(roleId);
      out.write("; \t\r\n");
      out.write("\r\n");
      out.write("function resizeIframes(obj) {\r\n");
      out.write("\tobj.style.height = 1100+ 'px';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("  When ticket open in Edit mode from List page\r\n");
      out.write(" \tAnd after updating the ticket again opening in Edit Mode .\r\n");
      out.write(" \tTo aviod such situation added the below Variable\r\n");
      out.write(" \tChanged By : Nagamanikanta(714599)\r\n");
      out.write(" */\r\n");
      out.write("var isInEditModeOpen = true;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('document').ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("    $.ajaxSetup({ cache: false });\r\n");
      out.write("\tvar parentmenuId =1;\r\n");
      out.write("\tvar parentMenuName=\"HelpDesk\";\r\n");
      out.write("\tif(roleIde==1){\r\n");
      out.write("\t\tparentmenuId=113;\r\n");
      out.write("\t\tparentMenuName=\"Create Master Ticket\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(parentmenuId==1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t $('#centeriframe').attr('src', 'HELPDESK_Create.htm');\t\t\r\n");
      out.write(" \t\t  myLayout.initContent('center'); \r\n");
      out.write("\t}\r\n");
      out.write("  \t\r\n");
      out.write("  \tvar html_SearchWindow=getSearchHtml_SearchWindow();\r\n");
      out.write("  \tvar html_ServiceWindow=getSearchHtml_ServiceWindow();\r\n");
      out.write("\r\n");
      out.write("  \t/*******Added by Poovamma(716302)-Right Side Search***********/\r\n");
      out.write("\t$('#myAccordion_searchWindow', window.parent.document).html(html_SearchWindow);\t\r\n");
      out.write("\t$(\"#lastframe\").attr(\"src\",\"UNIVERSAL_Searchh.htm\");\r\n");
      out.write(" \t$(\"#myAccordion_searchWindow\").accordion(accOpts_searchWindow);\t\t\r\n");
      out.write("\t$('#myAccordion_serviceWindow', window.parent.document).html(html_ServiceWindow);\t\r\n");
      out.write(" \t$(\"#myAccordion_serviceWindow\").accordion(accOpts_serviceWindow); \t\r\n");
      out.write(" \t$(\"#myAccordion_searchWindow\").filter(\":has(.ui-state-default)\").accordion(\"activate\", 0); \t\r\n");
      out.write(" \t$(\"#myAccordion_serviceWindow\").filter(\":has(.ui-state-active)\").accordion(\"activate\",false);\r\n");
      out.write(" \t$(\"#myAccordion_serviceWindow\").hide();\r\n");
      out.write(" \t/*******End Added by Poovamma(716302)***********/\r\n");
      out.write(" \tdisplaySubMenu(parentmenuId,parentMenuName);  \r\n");
      out.write("}); \r\n");
      out.write("/*******Added by Poovamma(716302)-Right Side Search***********/\r\n");
      out.write("function getSearchHtml_SearchWindow(){\r\n");
      out.write("\tvar html=\"<h2 align='left' ><a href='#' class='accor_head_search'>Search Window</a></h2>\";\t\r\n");
      out.write("\thtml+=\"<div class='sub_tab_bg'><iframe name='lastframe' id='lastframe' width='100%'  scrolling='no' frameborder='0' onload='javascript:resizeIframes(this);'/></div>\";\r\n");
      out.write("\treturn html;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSearchHtml_ServiceWindow(){\r\n");
      out.write("\tvar html=\"<h2 align='left' ><a href='#' class='accor_head_search'>Service Window Details</a></h2><div class='sub_tab_bg'><div id='serviceWindowDiv'></div><br><div id='firstDivId'></div><div id='secondDivId'></div></div>\";\r\n");
      out.write("\treturn html;\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pageY(elem) {\r\n");
      out.write("    return elem.offsetParent ? (elem.offsetTop + pageY(elem.offsetParent)) : elem.offsetTop;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var buffer = 10; //scroll bar buffer\r\n");
      out.write("function resizeIframe() {\r\n");
      out.write("    var height = window.innerHeight || document.body.clientHeight || document.documentElement.clientHeight;\r\n");
      out.write("    height -= pageY(document.getElementById('lastframe'))+ buffer ;\r\n");
      out.write("    height = (height < 0) ? 0 : height;\r\n");
      out.write("    document.getElementById('lastframe').style.height = height + 'px';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*******End Added by Poovamma(716302)-Right Side Search***********/\r\n");
      out.write(" function displaySubMenu(parentmenuId,parentMenuName){\t\r\n");
      out.write("\t //parent.$(\"#myAccordion_serviceWindow\").hide();\r\n");
      out.write("\t parent.$(\"#myAccordion_serviceWindow\").accordion(\"destroy\");\r\n");
      out.write("\t $(\"#lastframe\").attr(\"src\",\"UNIVERSAL_Searchh.htm\");\r\n");
      out.write("\t \r\n");
      out.write("\t parent.$(\"#myAccordion_searchWindow\").filter(\":has(.ui-state-default)\").accordion(\"activate\", 0); \t\r\n");
      out.write("\r\n");
      out.write("\t parent.$('#myAccordion_serviceWindow', window.parent.document).html(getSearchHtml_ServiceWindow());\r\n");
      out.write("\t parent.$(\"#myAccordion_serviceWindow\").hide();\r\n");
      out.write("\t var centerhref = \"\";\r\n");
      out.write("\t try{centerhref = centeriframe.location.href;}\r\n");
      out.write("\t catch (e){}\r\n");
      out.write("\t if(centerhref.indexOf(\"HELPDESK_Edit.htm\") != -1 && window.frames[\"centeriframe\"].inEditMode){\r\n");
      out.write("\t\t if(confirm(\"Do you want to continue with out updating the ticket?\")){\r\n");
      out.write("\t\t\t var detailTicketId = window.frames[\"centeriframe\"].document.getElementById(\"TICKET_ID\").value;\r\n");
      out.write("\t\t\t releaseTicket(detailTicketId,1);\r\n");
      out.write("\t\t }else{\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t  }\r\n");
      out.write("\t\t\r\n");
      out.write("\t  var getmailId=\"\";\r\n");
      out.write("\t if(centerhref.indexOf(\"convertMailtoHelpdesk.htm\") != -1){\r\n");
      out.write("\t\t\tgetmailId =  window.frames[\"centeriframe\"].document.getElementById(\"mailid\").value;\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t  if(centerhref.indexOf(\"convertMailtoHelpdesk.htm\") != -1 && getmailId != '' && window.frames[\"centeriframe\"].document.getElementById(\"ticketsubmit\").disabled == false){\r\n");
      out.write("\t\t\t if(confirm(\"Do you want to continue with out creating the ticket?\")){\r\n");
      out.write("\t\t\t\t var mailId = window.frames[\"centeriframe\"].document.getElementById(\"mailid\").value;\r\n");
      out.write("\t\t\t\t releaseTicket(mailId,4);\r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t  }\r\n");
      out.write(" \r\n");
      out.write("\t$('.topmenu a').removeClass('selected');\r\n");
      out.write("\t$('#'+parentmenuId).addClass('selected');\r\n");
      out.write("\t\t$.getJSON('menuList.htm', {\r\n");
      out.write("\t\t\tparentmenuId : parentmenuId\r\n");
      out.write("\t\t}, function(data) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tif (data.length != 0) {\r\n");
      out.write("\t\t\tvar treeLevelHTML =\"<input type = 'hidden' name = 'parentMenu' value = '\"+parentMenuName+\"'/><ul id='browser' class='filetree'>\";\r\n");
      out.write("\t\t\tvar options = [];\r\n");
      out.write("\t\t\t\t$.each(data, function(item) {\r\n");
      out.write("\t\t\t\t\tif(data[item].childExsists==\"false\"){\r\n");
      out.write("\t\t\t\t\tif(data[item].parentId==parentmenuId)\r\n");
      out.write("\t\t\t\t\ttreeLevelHTML+=\"<li id='\"+data[item].menuId+\"'><span class='folder'  id='\"+data[item].menuId+\"'  onclick=\\\"displayRight(this.id,'\"+parentmenuId+\"','\"+data[item].menuName+\"','\"+parentMenuName+\"')\\\">\"+ data[item].menuName+\"</span></li>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tvar childMenuId=data[item].menuId;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttreeLevelHTML+=\"<li id='\"+data[item].menuId+\"'><span class='folder' id='\"+data[item].menuId+\"' onclick=\\\"displayRight(this.id,'\"+parentmenuId+\"','\"+data[item].menuName+\"','\"+parentMenuName+\"')\\\">\"+ data[item].menuName+\"</span><ul>\";\r\n");
      out.write("\t\t\t\t\t\tvar options = [];\r\n");
      out.write("\t\t\t\t\t\t$.each(data, function(item) {\r\n");
      out.write("\t\t\t\t\t\t\tif(data[item].parentId==childMenuId){\r\n");
      out.write("\t\t\t\t\t\t\ttreeLevelHTML+=\"<li id='\"+data[item].menuId+\"'><span class='file' id='\"+data[item].menuId+\"' onclick=\\\"displayRight(this.id,'\"+parentmenuId+\"','\"+data[item].menuName+\"','\"+parentMenuName+\"')\\\">\"+ data[item].menuName+\"</span></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\ttreeLevelHTML+=\"</ul></li>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\ttreeLevelHTML+=\"</ul>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(roleIde==6){\r\n");
      out.write("\t\t\t\t\ttreeLevelHTML+=\"<br></br><div id=\\\"onlineUsers\\\"><font color=\\\"#0000FF\\\">Number of online user(s):\"+ ");
      out.print(counter.getActiveSessionNumber() );
      out.write("+\"</font></div>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t $('div.ui-layout-west').html(treeLevelHTML);\r\n");
      out.write("\t\t\t\t myLayout.initContent('west');\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t$(\"#browser\").treeview({\r\n");
      out.write("\t\t\t\t\tcollapsed: true,\r\n");
      out.write("\t\t\t\t\tanimated: \"medium\",\r\n");
      out.write("\t\t\t\t\tcontrol:\"#sidetreecontrol\",\r\n");
      out.write("\t\t\t\t\tpersist: \"location\"\r\n");
      out.write("\t\t\t\t\t/*animated:\"normal\",\r\n");
      out.write("\t\t\t\t\tpersist: \"cookie\"*/\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t$.getJSON('bulletinMessage.htm', {\r\n");
      out.write("\t\t}, function(data) {\r\n");
      out.write("\t\t\tif (data.length != 0) {\r\n");
      out.write("\t\t\t\tvar pausecontent2=new Array();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\ttreeLevelHTML+=\"<br></br><div id='stcikyDivId' class='board'>\"\r\n");
      out.write("\t\t\t\t\t+\"<div id='bulletinBoard'><center><font color='white'>Bulletin Board</font></center></div><marquee behavior='scroll' direction='up' \"+\r\n");
      out.write("\t\t\t\t\t\"scrollamount='3' onmouseover='this.stop();' onmouseout='this.start();'  style='width:100%;'>\";\r\n");
      out.write("\t\t\t\tvar options = [];\r\n");
      out.write("\t\t\t\t$.each(data, function(item) {\r\n");
      out.write("\t\t\t\t\ttreeLevelHTML+=\"<h4><u><center>\"+data[item].BULLETIN_HEADER+\"</center></u></h4><span><center>\"+data[item].BULLETIN_DESCRIPTION+\"</center><br></span>\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttreeLevelHTML+=\"</marquee></div>\";\r\n");
      out.write("\r\n");
      out.write("\t\t $('div.ui-layout-west').html(treeLevelHTML);\r\n");
      out.write("\t\t\t myLayout.initContent('west');\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t$(\"#browser\").treeview({\r\n");
      out.write("\t\t\t\tcollapsed: true,\r\n");
      out.write("\t\t\t\tanimated: \"medium\",\r\n");
      out.write("\t\t\t\tcontrol:\"#sidetreecontrol\",\r\n");
      out.write("\t\t\t\tpersist: \"location\"\r\n");
      out.write("\t\t\t\t/*animated:\"normal\",\r\n");
      out.write("\t\t\t\tpersist: \"cookie\"*/\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$('div.ui-layout-west').html(\"\");\r\n");
      out.write("\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tparent.myLayout.open('west');\r\n");
      out.write("  if(parentmenuId==5)\r\n");
      out.write("  {//L2: 2786\r\n");
      out.write("\t  $('#centeriframe').attr('src', 'Reports.htm');\r\n");
      out.write("\t  myLayout.close('west');\r\n");
      out.write("  }else if(parentmenuId==3)\r\n");
      out.write("\t{\r\n");
      out.write("\t  \tCHILD_MENU_ID = 39;\t// This variable is referring in commonlistpage.js for list page column selection  window ; Changed By : 714599\r\n");
      out.write("\t\t$('#centeriframe').attr('src', 'UNIVERSAL_ListPage.htm?menuId=39&parentMenuId='+parentmenuId+'&menuName=New&parentMenuName=NOC-Alerts'); \r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(parentmenuId==4)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tCHILD_MENU_ID = 41;\t// This variable is referring in commonlistpage.js for list page column selection  window ; Changed By : 714599\r\n");
      out.write("\t\t$('#centeriframe').attr('src', 'UNIVERSAL_ListPage.htm?menuId=41&parentMenuId='+parentmenuId+'&menuName=New&parentMenuName=Mail-Tracker'); \r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t}\t\r\n");
      out.write("\telse if(parentmenuId==1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(roleIde==31){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'MASTER_Create.htm');\r\n");
      out.write("\t\t\tmyLayout.close('west');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t$('#centeriframe').attr('src', 'HELPDESK_Create.htm');\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(parentmenuId==6)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$('#centeriframe').attr('src', 'CONTACTUS_HelpDeskAndEscalation.htm'); \r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\tmyLayout.close('west');\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(parentmenuId==32)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t//$('#centeriframe').attr('src', 'ADMIN_DataResetCache.htm'); \r\n");
      out.write("\t\t$('#centeriframe').attr('src','ADMIN_EditGroup.htm');\r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(parentmenuId==115)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$('#centeriframe').attr('src', 'BULLETINBOARD_Create.htm'); \r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t}else if(parentmenuId==114){\r\n");
      out.write("\t\t$('#centeriframe').attr('src','UNIVERSAL_ListPage.htm?menuId=114&parentMenuId='+parentmenuId+'&menuName=View Master Ticket&parentMenuName=Helpdesk'); \r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\tmyLayout.close('west');\r\n");
      out.write("\t}else if(parentmenuId==113){\r\n");
      out.write("\t\t$('#centeriframe').attr('src', 'MASTER_Create.htm');\r\n");
      out.write("\t\tmyLayout.close('west');\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getWorkLoad(groupMember,memberName)\r\n");
      out.write("{\r\n");
      out.write("var memberworkLoadHTML = \"<div class = 'MYDIV'><table class='myDataTable' width='100%'><tr><th>\"+memberName+'('+groupMember+')'+\"</th></tr></table><table class='myDataTable' width='100%'><tr><th colspan='4'>No. Of Tickets</th></tr><tr><th>CATEGORY</th><th>HIGH</th><th>MEDIUM</th><th>LOW</th></tr>\";\r\n");
      out.write("var lowcount=0;\r\n");
      out.write("var mediumcount=0;\r\n");
      out.write("var highcount=0;\r\n");
      out.write("$.getJSON('groupMemberWorkLoad.htm', {\r\n");
      out.write("\t\tgroupMember : groupMember\r\n");
      out.write("\t}, function(data) {\r\n");
      out.write("\t\tif (data.length != 0) {\r\n");
      out.write("\t\t\tvar options = [];\r\n");
      out.write("\t\t\t$.each(data, function(item) {\r\n");
      out.write("\t\t\t\tlowcount = lowcount+data[item].low;\r\n");
      out.write("\t\t\t\tmediumcount = mediumcount+data[item].medium;\r\n");
      out.write("\t\t\t\thighcount = highcount+data[item].high;\r\n");
      out.write("\t\t\t\tmemberworkLoadHTML=memberworkLoadHTML+\"<tr><td>\"+data[item].CATEGORY+\"</td><td>\"+data[item].high+\"</td><td>\"+data[item].medium+\"</td><td>\"+data[item].low+\"</td></tr>\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmemberworkLoadHTML=memberworkLoadHTML+\"<tr><td>TOTAL</td><td>\"+highcount+\"</td><td>\"+mediumcount+\"</td><td>\"+lowcount+\"</td><tr></table></div>\";\r\n");
      out.write("\t\t\t$('#secondDivId').html(memberworkLoadHTML); \r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#secondDivId').html(\"<div class = 'MYDIV'><table class='myDataTable' width='100%'><tr><th>\"+memberName+'('+groupMember+')'+\"</th></tr><tr><th>No Tickets Assigned</th></tr></table></div>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("var CHILD_MENU_ID = 0;\t// This variable is referring in commonlistpage.js for list page column selection  window ; Changed By : 714599\r\n");
      out.write("\tfunction displayRight(menuId,parentMenuId,menuName,parentMenuName) {\r\n");
      out.write("\t\tparent.$(\"#myAccordion_serviceWindow\").hide();\r\n");
      out.write("\t\t$(\"#lastframe\").attr(\"src\",\"UNIVERSAL_Searchh.htm\");\r\n");
      out.write("\t\tparent.$(\"#myAccordion_searchWindow\").filter(\":has(.ui-state-default)\").accordion(\"activate\", 0); \t\r\n");
      out.write("\t\tisInEditModeOpen = true; // This is referring in HELPDESK_Edit.js to check whether to open the ticket in Edit mode or not when open in Edit from List page\r\n");
      out.write("\t \tCHILD_MENU_ID = menuId;\t// This variable is referring in commonlistpage.js for list page column selection window ; Changed By : 714599\r\n");
      out.write("\t\t var centerhref = \"\";\r\n");
      out.write("\t\t try{centerhref = centeriframe.location.href;}\r\n");
      out.write("\t\t catch (e){}\r\n");
      out.write("\t\t if(centerhref.indexOf(\"HELPDESK_Edit.htm\") != -1 && window.frames[\"centeriframe\"].inEditMode){\r\n");
      out.write("\t\t\t if(confirm(\"Do you want to continue with out updating the ticket?\")){\r\n");
      out.write("\t\t\t\t var detailTicketId = window.frames[\"centeriframe\"].document.getElementById(\"TICKET_ID\").value;\r\n");
      out.write("\t\t\t\t releaseTicket(detailTicketId,1);\r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t  }\r\n");
      out.write("\r\n");
      out.write("\t\t var getmailId=\"\";\r\n");
      out.write("\t\t if(centerhref.indexOf(\"convertMailtoHelpdesk.htm\") != -1){\r\n");
      out.write("\t\t\t\tgetmailId =  window.frames[\"centeriframe\"].document.getElementById(\"mailid\").value;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t if(centerhref.indexOf(\"convertMailtoHelpdesk.htm\") != -1 && getmailId != ''  && window.frames[\"centeriframe\"].document.getElementById(\"ticketsubmit\").disabled == false){\r\n");
      out.write("\t\t\t if(confirm(\"Do you want to continue without creating the ticket?\")){\r\n");
      out.write("\t\t\t\t var mailId = window.frames[\"centeriframe\"].document.getElementById(\"mailid\").value;\r\n");
      out.write("\t\t\t\t releaseTicket(mailId,4);\r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t blockUI();\r\n");
      out.write("\t\tif(menuId == '36' || menuId == '37' || menuId == '22')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'construction.htm'); \r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId == '7'){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'HELPDESK_Create.htm'); \r\n");
      out.write("\t\t}else if(menuId == '65'){\t\t\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'ADMIN_DataResetCache.htm'); \r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId == '98'){\t\t\t\t\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'ADMIN_WorkflowResetCache.htm'); \r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if((menuId=='101')||(menuId=='100')){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','ADMIN_ViewGroup.htm');\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId=='102'){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','ADMIN_ChangeGroup.htm');\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId=='103'){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','ADMIN_AddGroup.htm');\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if((menuId=='104')){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','ADMIN_ViewGroup.htm');\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId=='113'){\t\t\t\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','MASTER_Create.htm');\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if((menuId=='116')){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','BULLETINBOARD_Create.htm');\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if((menuId=='117')){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','BULLETINBOARD_Remove.htm');\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId=='134'){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','ADMIN_CreateGroup.htm');\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId=='135' || menuId=='133'){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','ADMIN_EditGroup.htm');\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId=='136' || menuId=='137'){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'ADMINCONSOLE_AddLocation.htm');\r\n");
      out.write("\t\t\tmyLayout.close('west');\r\n");
      out.write("\t\t}else if(menuId=='139' || menuId=='140' || menuId=='141'){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'ADMIN_CategoryDisplayConsole.htm');\r\n");
      out.write("\t\t\tmyLayout.close('west');\r\n");
      out.write("\t\t}//Added for Role menu under settings\r\n");
      out.write("\t\telse if(menuId == '143'){\t\t\t\t\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'ADMIN_RoleManipulation.htm'); \r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(menuId == '138'){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','ADMIN_ModifyLocation.htm');\r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId == '144'){\t\t\t\t\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'ADMIN_ExcelUpload.htm'); \r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId == '145'){\t\t\t\t\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'ADMIN_ExcelUpload.htm'); \r\n");
      out.write("\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\telse if(menuId == '146'){\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src','HELPDESK_EmployeeProfile.htm');\r\n");
      out.write("\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t}else if(menuId == '197'){\r\n");
      out.write("\t\t\t\t$('#centeriframe').attr('src','ADMIN_CreateUser.htm');\r\n");
      out.write("\t\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t\t\t}else if(menuId == '198'){\r\n");
      out.write("\t\t\t\t\t$('#centeriframe').attr('src','ADMIN_AddLHProject.htm');\r\n");
      out.write("\t\t\t\t\tmyLayout.initContent('center');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$('#centeriframe').attr('src', 'UNIVERSAL_ListPage.htm?menuId='+ menuId+'&parentMenuId='+parentMenuId+'&menuName='+menuName+'&parentMenuName='+parentMenuName);\r\n");
      out.write("\t\t\tmyLayout.initContent('center');\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction jbarOnSuccess(message){\r\n");
      out.write("\t\t// Special Handling for IE\r\n");
      out.write("\t\tisIE = $.browser.msie && !$.support.opacity; // Detects IE6,7,8.  IE9 supports opacity.  Feature detection alone gave a false positive on at least one phone browser and on some development versions of Chrome, hence the user-agent test.\r\n");
      out.write("\t\tisIE6OrIE9 = isIE && $.browser.version ==6 || $.browser.version ==9;\r\n");
      out.write("\t\tif(isIE6OrIE9==true)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(\"#jbarmessage\").bar({\r\n");
      out.write("\t\t\t\tcolor \t\t\t : 'BLACK',\r\n");
      out.write("\t\t\t\tbackground_color : '#C8DD9C',\r\n");
      out.write("\t\t\t\tposition\t\t : 'bottom',\r\n");
      out.write("\t\t\t\tremovebutton     : true,\r\n");
      out.write("\t\t\t\tmessage\t\t\t : message,\r\n");
      out.write("\t\t\t\ttime\t\t\t : 12000\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t}else\r\n");
      out.write("\t\t{\t\t\r\n");
      out.write("\t\t$(\"#jbarmessage\").bar({\r\n");
      out.write("\t\t\tcolor \t\t\t : 'BLACK',\r\n");
      out.write("\t\t\tbackground_color : '#C8DD9C',\r\n");
      out.write("\t\t\tposition\t\t : 'bottom',\r\n");
      out.write("\t\t\tremovebutton     : true,\r\n");
      out.write("\t\t\tmessage\t\t\t : message,\r\n");
      out.write("\t\t\ttime\t\t\t : 12000\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction jbarOnFailure(message){\r\n");
      out.write("\t\t// Special Handling for IE\r\n");
      out.write("\t\tisIE = $.browser.msie && !$.support.opacity; // Detects IE6,7,8.  IE9 supports opacity.  Feature detection alone gave a false positive on at least one phone browser and on some development versions of Chrome, hence the user-agent test.\r\n");
      out.write("\t\tisIE6OrIE9 = isIE && $.browser.version ==6 || $.browser.version ==9;\r\n");
      out.write("\t\tif(isIE6OrIE9==true)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(\"#jbarmessage\").bar({\r\n");
      out.write("\t\t\t\tcolor \t\t\t : 'BLACK',\r\n");
      out.write("\t\t\t\tbackground_color : 'RED',\r\n");
      out.write("\t\t\t\tposition\t\t : 'bottom',\r\n");
      out.write("\t\t\t\tremovebutton     : true\t,\r\n");
      out.write("\t\t\t\tmessage\t\t\t : message,\r\n");
      out.write("\t\t\t\ttime\t\t\t : 12000\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else\r\n");
      out.write("\t\t{\t\t\r\n");
      out.write("\t\t$(\"#jbarmessage\").bar({\r\n");
      out.write("\t\t\tcolor \t\t\t : 'BLACK',\r\n");
      out.write("\t\t\tbackground_color : 'RED',\r\n");
      out.write("\t\t\tposition\t\t : 'bottom',\r\n");
      out.write("\t\t\tremovebutton     : true\t,\r\n");
      out.write("\t\t\tmessage\t\t\t : message,\r\n");
      out.write("\t\t\ttime\t\t\t : 12000\r\n");
      out.write("\t\t});\r\n");
      out.write("\t} \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction releaseTicket(ticketId,menuId){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar jsonobj = '{\"JSONARRAY\":['+'{\"TICKET_ID\":\"'+ticketId+'\",\"MENU_ID\":\"'+menuId+'\"}'+']}';\r\n");
      out.write("\t\t$.getJSON('unlockTickets.htm', {json:jsonobj}, function(data) {\r\n");
      out.write("\t\t\tif(data.status==\"Success\"){\r\n");
      out.write("\t\t\t \t window.frames[\"centeriframe\"].inEditMode = false;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction ticketUnlocking(){\r\n");
      out.write("\t\t\r\n");
      out.write("  \t\t var centerhref = \"\";\r\n");
      out.write("\t\t try{centerhref = centeriframe.location.href;}\r\n");
      out.write("\t\t catch (e){}\r\n");
      out.write("\t\t if(centerhref.indexOf(\"HELPDESK_Edit.htm\") != -1 && window.frames[\"centeriframe\"].inEditMode){\r\n");
      out.write("\t\t\t\t var detailTicketId = window.frames[\"centeriframe\"].document.getElementById(\"TICKET_ID\").value;\r\n");
      out.write("\t\t\t\t releaseTicket(detailTicketId,1);\r\n");
      out.write("\t\t  } \r\n");
      out.write("\t\t if(isChng==false)\r\n");
      out.write("\t\t {\t\t\t\r\n");
      out.write("\t\t  window.location.href='Logout.htm';\r\n");
      out.write("\t\t }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\tfunction iConnectLogOut(){\r\n");
      out.write("\t   \t var centerhref = \"\";\r\n");
      out.write("\t\t try{centerhref = centeriframe.location.href;}\r\n");
      out.write("\t\t catch (e){} \r\n");
      out.write("\t\t if(centerhref.indexOf(\"HELPDESK_Edit.htm\") != -1 && window.frames[\"centeriframe\"].inEditMode){\r\n");
      out.write("\t\t\t if(confirm(\"Do you want to continue with out updating the ticket?\")){\r\n");
      out.write("\t\t\t\t var detailTicketId = window.frames[\"centeriframe\"].document.getElementById(\"TICKET_ID\").value;\r\n");
      out.write("\t\t\t\t releaseTicket(detailTicketId,1);\r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t  }\r\n");
      out.write("\r\n");
      out.write("\t\twindow.location.href='Logout.htm'; \r\n");
      out.write("\t}\r\n");
      out.write("\tif(roleIde==6){\r\n");
      out.write("\t\tvar auto_refresh = setInterval(\r\n");
      out.write("\t    \t\tfunction ()\r\n");
      out.write("\t    \t\t\t{   \t\t\t\t\t\r\n");
      out.write("\t    \t\t\t \t\t\t$('#onlineUsers').load('numberOfUsers.htm', function(data){\r\n");
      out.write("\t        \t\t\t \t\t$('#onlineUsers').html('<font color=\\\"#0000FF\\\">Number of online user(s):'+ data+'</font>')}).fadeIn(\"slow\");\r\n");
      out.write("\t    \t\t}, 10000); // autorefresh the content of the div after\r\n");
      out.write("\t    \t\t\t  //every 10000 milliseconds(10sec)\r\n");
      out.write("\t\t}\r\n");
      out.write("\tfunction blockUI(){\r\n");
      out.write("\t\t$('.ui-layout-center').block({ css: {   \r\n");
      out.write("            border: 'none', \r\n");
      out.write("            padding: '15px', \r\n");
      out.write("            backgroundColor: '#000', \r\n");
      out.write("            '-webkit-border-radius': '10px', \r\n");
      out.write("            '-moz-border-radius': '10px', \r\n");
      out.write("            opacity: .5, \r\n");
      out.write("            color: '#fff' \r\n");
      out.write("        } });\r\n");
      out.write("    }\r\n");
      out.write("    function unblockUI(){\r\n");
      out.write("    \t$('.ui-layout-center').unblock();  \r\n");
      out.write("    }     \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Header Menu -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String cssPath = (String)getServletContext().getInitParameter("cssDirPath");

String jsPath = (String)getServletContext().getInitParameter("jsDirPath");
 
String empId = (String) request.getSession().getAttribute(
"userLoginId");
User userObj = (User) request.getSession().getAttribute(
        empId);
String empName = userObj.getUserName();
String currentUserRole = userObj.getUserRole();
long currentUserRoleID = 0;
List<WORKFLOW_Role> userRoleList = userObj.getUserRoleList();

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cssPath);
      out.write("/gamification.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("#cboxTitle{display:none !important;}\r\n");
      out.write("</style>\r\n");
 String token = null; 
      out.write("\r\n");
      out.write("<div class=\"ui-layout-north\" style=\"padding: 0px;height:100px!important;\">\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("<div style=\"float:left;\" class=\"title\"><img src=\"images/iConnect_Logo.png\" title=\"Logo\"/></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div> \r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"topnav\" class=\"topnav\">\r\n");
      out.write("\t\r\n");
      out.write("       \r\n");
      out.write("\t<div style=\"text-align:right;\"> \r\n");
      out.write("      Welcome <strong>");
      out.print(empName );
      out.write("</strong> <a href=\"login\" class=\"signin\"><img src=\"images/profile.png\" alt=\"My Profile\" title=\"My Profile\"/></a> <a href=\"#\" onclick=\"iConnectLogOut();\"><img src=\"images/logout.png\" alt=\"Logout\" title=\"Logout\"/></a>\r\n");
      out.write("      <img src=\"images/Capgemini_Header_Logo.png\"/>  \r\n");
      out.write("        \t\r\n");
      out.write("   \t</div> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t<fieldset id=\"signin_menu\">\r\n");
      out.write("\t<form id = \"changeRole\" action=\"/iconnect/RoleChanged.htm\" method=\"POST\">\r\n");
      out.write("\t<select name = \"userRoleId\" id = \"userRoleId\" onchange=\"isChange()\">\r\n");
      out.write("\t");

		for(int i = 0; i < userRoleList.size(); i++){
			WORKFLOW_Role role = userRoleList.get(i);
			if(currentUserRole.equalsIgnoreCase(role.getRoleName())){
				currentUserRoleID = role.getRoleId();
		
      out.write("\r\n");
      out.write("\t\t<option value=\"");
      out.print( role.getRoleId());
      out.write("\" selected = \"selected\">");
      out.print( role.getRoleName());
      out.write("</option>\r\n");
      out.write("\t\t");

			}else{
		
      out.write("\r\n");
      out.write("\t\t<option value=\"");
      out.print( role.getRoleId());
      out.write('"');
      out.write('>');
      out.print( role.getRoleName());
      out.write("</option>\r\n");
      out.write("\t\t");

			}
	}
		
		
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\t  </select>\r\n");
      out.write("\t  </form>\r\n");
      out.write("      \r\n");
      out.write("  </fieldset>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"topmenu\">\r\n");

String headerName = "";
String headerId="";
String headerClass="";
 List<COMMON_Menu> parentMenuList=(List<COMMON_Menu>) request.getSession().getAttribute("parentMenu");
for(int i = 0; i < parentMenuList.size(); i++){

	COMMON_Menu parentMenuObj = parentMenuList.get(i);
    headerName = parentMenuObj.getMenuName();
    headerId=parentMenuObj.getMenuId().toString();
    if(headerName.contains("Contact"))
    {
    	headerClass="Escalations-Contact";
    }else
    {
    	headerClass=headerName;
    }

      out.write("\r\n");
      out.write("<a href=\"#\"  onclick=\"displaySubMenu(this.id,'");
      out.print(headerName);
      out.write("')\" id=\"");
      out.print(headerId );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(headerName);
      out.write("</a>\r\n");

}
 
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsPath);
      out.write("/custom/UNIVERSAL_Security.js\"></script>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var loggedinroleID = \"");
      out.print(currentUserRoleID);
      out.write("\";\r\n");
      out.write("var EMPLOYEE_ID = \"");
      out.print(empId);
      out.write("\";\r\n");
      out.write("var ROLE_ID = \"");
      out.print(currentUserRoleID);
      out.write("\";\r\n");
      out.write("var isChng=false;\r\n");
      out.write("function isChange()\r\n");
      out.write("{\r\n");
      out.write("\tisChng=true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 token = (String)request.getSession().getAttribute("OWASP_CSRFTOKEN"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"OWASP_CSRFTOKEN\" value=\"");
      out.print( token );
      out.write("\" />");
      out.write("\r\n");
      out.write("<!-- End of Header Menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- West Panel -->\r\n");
      out.write("<div class=\"ui-layout-west nyroModal\" style=\"padding:0px;\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- End of West Panel -->\r\n");
      out.write("\r\n");
      out.write("<!-- East Panel -->\r\n");
      out.write("<div class=\"ui-layout-east\">\r\n");
      out.write("<div id=\"myAccordion_searchWindow\">\r\n");
      out.write("</div>\r\n");
      out.write(" <div id=\"myAccordion_serviceWindow\">\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- End of East Panel -->\r\n");
      out.write("\r\n");
      out.write("<!-- Center Panel -->\r\n");
      out.write("<div class=\"ui-layout-center\" style=\"padding:0px; margin:0px; background-color:#ffffff;overflow-x: scroll; !important\"> \r\n");
      out.write("\t<iframe id=\"centeriframe\" name=\"centeriframe\" width=\"99%\" height=\"98%\"></iframe>\t \r\n");
      out.write(" </div> \r\n");
      out.write("\r\n");
      out.write("<!-- End of Center Panel -->\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<div class=\"ui-layout-south\"> \r\n");
      out.write("\tCopyright &copy; IGATE. All Rights Reserved.\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("<!-- End of Footer -->\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("<input type=\"hidden\" id=\"jbarmessage\" name=\"jbarmessage\"></input>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
