package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.*;
import java.util.*;
import com.igate.iconnect.BO.COMMON_Menu;
import com.igate.iconnect.BO.WORKFLOW_Role;
import com.igate.iconnect.BO.User;
import java.util.List;

public final class searchHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fmethod_005fid_005faction;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fmethod_005fid_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fmethod_005fid_005faction.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String jsDirPath = (String)getServletContext().getInitParameter("jsDirPath");  
   String cssDirPath = (String)getServletContext().getInitParameter("cssDirPath"); 

      out.write('\r');
      out.write('\n');
  String empId = (String) request.getSession().getAttribute(
"userLoginId");
User userObj = (User) request.getSession().getAttribute(
        empId);
String empName = userObj.getUserName();
String location = userObj.getLocationCity();
String currentUserRole = userObj.getUserRole();
List<WORKFLOW_Role> userRoleList = userObj.getUserRoleList();
int gradeLevel=0;
if(userObj.getWorkSpacePlanning_Grade_Level()!=null){
	gradeLevel= Integer.parseInt(userObj.getWorkSpacePlanning_Grade_Level());
}
long currentUserRoleID = 0;
String SSOFlag ="NA";
int gradeAccess=userObj.getWorkSpacePlanning_Access();
//ResourceBundle bundle = ResourceBundle.getBundle("smartsearch");
//String iConnectURL=bundle.getString("iConnectURL");
String schema = request.getScheme();
		String serverName = request.getServerName();
		int serverPort = request.getServerPort();
		String contextPath = request.getContextPath();
		String iConnectURL = schema + "://" + serverName + ":" + serverPort + contextPath;

      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>IConnect : Unified Service Desk for Life & Health - Search</title>\r\n");
      out.write("<link href=\"");
      out.print(cssDirPath);
      out.write("/styles.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(cssDirPath);
      out.write("/pagination.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(cssDirPath);
      out.write("/jbar_style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(cssDirPath);
      out.write("/ui.base.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(cssDirPath);
      out.write("/ui.theme.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(cssDirPath);
      out.write("/jquery.autocomplete.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/json.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.pagination.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.bar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.dotdotdot.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/jquery.session.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/custom/search.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/custom/userSolution.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(jsDirPath);
      out.write("/custom/User.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("if(top.location.href.substring(0, top.location.href.lastIndexOf(\"/\")+1)!=window.location.href.substring(0, window.location.href.lastIndexOf(\"/\")+1)){\r\n");
      out.write("\ttop.location=window.location;\r\n");
      out.write("}\r\n");
      out.write("var context = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("loc = String(window.location);\r\n");
      out.write("var urlAppl = loc.substr(0,loc.indexOf(context));\r\n");
      out.write("var home = '");
      out.print(iConnectURL);
      out.write("';\r\n");
      out.write("var gradeLevel=");
      out.print(gradeLevel);
      out.write(";\r\n");
      out.write("var gradeAccess=");
      out.print(gradeAccess);
      out.write(";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var usrLocation = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.location}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("var subject = \"\";\r\n");
      out.write("var tagList = null ;\r\n");
      out.write("var availableTags = new Array();\r\n");
      out.write("//Added for Role Change in search page\r\n");
      out.write("$(\".signin\").click(function (e) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("    $(\"fieldset#signin_menu\").toggle();\r\n");
      out.write("    $(\".signin\").toggleClass(\"menu-open\");\r\n");
      out.write("});\r\n");
      out.write("var ssoFlag =\"");
      out.print(SSOFlag);
      out.write("\";\r\n");
      out.write("var srchTxtVar=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.srchTxt}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("//End Added for Role Change in search page\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("if(parseInt(gradeLevel,10)>=8 && parseInt(gradeAccess,10)>0){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#WorkspacePlanningLi\").attr('style','display:block');\r\n");
      out.write("\t$(\"#WorkspacePlanning\").show();\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("$.getJSON('bulletinMessage.htm', {\r\n");
      out.write("\t\t}, function(data) {\r\n");
      out.write("\t\t\tif (data.length != 0) {\r\n");
      out.write("\t\t\t\tvar bulltinHtml=\"\";\r\n");
      out.write("\t\t\t\tbulltinHtml=bulltinHtml+\"<div id='bulletinBoard'><center><strong>Bulletin Board</strong></center></div>\";\r\n");
      out.write("\t\t\t\tbulltinHtml=bulltinHtml+\"<marquee behavior='scroll' direction='up' scrollamount='3' onmouseover='this.stop();' onmouseout='this.start();' style='width:100%;'>\";\r\n");
      out.write("\t\t\t\tvar options = [];\r\n");
      out.write("\t\t\t\t$.each(data, function(item) {\r\n");
      out.write("\t\t\t\t\tbulltinHtml+=\"<h4><u><center>\"+data[item].BULLETIN_HEADER+\"</center></u></h4><span><center>\"+data[item].BULLETIN_DESCRIPTION+\"</center><br></span>\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tbulltinHtml+=\"</marquee>\";\r\n");
      out.write("\t\t\t\t$('#bulletinBoard').html(bulltinHtml);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('#bulletinBoard').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#textfield').click(function(event){\r\n");
      out.write("\t\t event.stopPropagation(); \r\n");
      out.write("\t\t if($(this).val() == 'Search Your Query')\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\t $(this).val('');\r\n");
      out.write("\t\t\t $(this).css('color' , '#000000');\r\n");
      out.write("\t\t }\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#button').click(function(event){\r\n");
      out.write("\t\t event.stopPropagation(); \r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('#tagTable').click(function(event){\r\n");
      out.write("\t\t event.stopPropagation(); \r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(document).mouseup(function (e){\r\n");
      out.write("\t\t\t    var container = $('#container').find('ul');\r\n");
      out.write("\t\t\t    if (container.has(e.target).length === 0){\r\n");
      out.write("\t\t\t        container.hide();\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#textfieldContainer\").keyup(function(event){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tswitch(event.keyCode) {\r\n");
      out.write("\t\t\tcase 33:\r\n");
      out.write("\t\t\t\tmovePrevOption();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 34:\r\n");
      out.write("\t\t\t\tmoveNextOption();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 38:\r\n");
      out.write("\t\t\t\tmovePrevOption();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 40:\r\n");
      out.write("\t\t\t\tmoveNextOption();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 13:\r\n");
      out.write("\t\t\t\tif($('li').hasClass('ui-state-hover'))\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$(\"#textfield\").val($('#selectedOption').text());\r\n");
      out.write("\t\t\t\t\t$('#container').find('ul').remove();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#container').find('ul').remove();\r\n");
      out.write("\t\t\t\t\tsubmitTxt();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tdefault:\r\n");
      out.write("\t\t\t\tshowSuggestions();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/**\r\n");
      out.write("\tAdded by Mohit(816452)/307 to add the Top Ten Viewed Documents onLoad on the screen\r\n");
      out.write("\t**/\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${backToSrch}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" == \"true\" && srchTxtVar.replace(/[^a-zA-Z 0-9]+/g,'') != \"Search Your Query\" )\r\n");
      out.write("\t{\r\n");
      out.write("\t\t    $('#textfield').css('color' , '#666666');\r\n");
      out.write("\t\t\t$('#textfield').val(srchTxtVar.replace(/[^a-zA-Z 0-9]+/g,''));\r\n");
      out.write("\t\t\tsrchTxtList = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.srchTxtList}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t\tsrchTxtList = String(srchTxtList);\r\n");
      out.write("\t\t\tvar srchTxtArray = new Array();\r\n");
      out.write("\t\t\tsrchTxtArray = srchTxtList.split(\",\");\r\n");
      out.write("\t\t\t\t//$('#solutionBoard').show();\r\n");
      out.write("\t\t\t   $.each(srchTxtArray , function(count){\r\n");
      out.write("\t\t\t\t\t$('#tagName').append('<option>'+srchTxtArray[count]+'</option>');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tsubmitTxt();\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajaxSetup({ cache: false });\r\n");
      out.write("\t$.ajaxSetup({ async: false });\r\n");
      out.write("\t$.getJSON(\"getTopTenViewedDocuments.htm\",function(data){\r\n");
      out.write("\t\tvar docArr = data;\r\n");
      out.write("\t\tvar link = \"\";\r\n");
      out.write("\t\tvar id = \"\";\r\n");
      out.write("        var isTag = false;\r\n");
      out.write("        var isPolicyDoc = false;\r\n");
      out.write("      \tvar imgSrc = \"\";\r\n");
      out.write("        var alt = \"\";\r\n");
      out.write("        var type=\"\";\r\n");
      out.write("        var downloadFileType=\"doc|docx|ppt|pptx|xls|xlsx\"\r\n");
      out.write("        var usageCount=\"\";\r\n");
      out.write("        var newcontent=\"\";\r\n");
      out.write("        if(docArr.length>0){\r\n");
      out.write("        \t $(\"#smartSearchImg\").hide();\r\n");
      out.write("\t\t  for (count = 0; count < docArr.length; count++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\tid = docArr[count].id;\r\n");
      out.write("\t\t\t\t$.ajaxSetup({async:false});\r\n");
      out.write("\t\t\t\t$.ajax({\t\r\n");
      out.write("\t\t\t\t\t  type: 'GET',\r\n");
      out.write("\t\t\t\t\t\turl :'getUsageCount.htm', \r\n");
      out.write("\t\t\t\t\t\tdata:{docId:id} ,\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tusageCount=data;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tif(docArr[count].id.indexOf('TG') != -1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tisTag = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if(docArr[count].id.indexOf('DC') != -1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tlink = docArr[count].srch_links ;\r\n");
      out.write("\t\t\t\t\timgSrc=\"images/searchAI/Doc.png\";\r\n");
      out.write("\t\t\t\t\talt=\"Document\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if(docArr[count].id.indexOf('PD_') != -1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tisPolicyDoc = true;\r\n");
      out.write("\t\t\t\t\tlink = docArr[count].srch_links ;\r\n");
      out.write("\t\t\t\t\timgSrc=\"images/searchAI/Doc.png\";\r\n");
      out.write("\t\t\t\t\talt=\"Policy Document\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tlink = \"\";\r\n");
      out.write("\t\t\t\t\timgSrc=\"images/searchAI/ticket.png\";\r\n");
      out.write("\t\t\t\t\talt=\"IConnect Ticket\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(isTag)\r\n");
      out.write("\t\t\t\t  {\r\n");
      out.write("\t\t\t\t\t if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<div>\";\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t \t  newcontent +=\"<div class=\\\"result\\\">\";\r\n");
      out.write("\t\t\t\t\t  newcontent +=\"<a href=\\\"goSearchResult.htm?id=\"+id+\"&docLink=\"+link+\"&srchTxt=\"+$('#textfield').val().replace(/[^a-zA-Z 0-9]+/g,'')+\"&isTag=\"+isTag+\"\\\" onclick=updateUsageCount('\"+id+\"') ><img src=\\\"images/searchAI/User.png\\\" alt=\\\"User Solution\\\"/> \"+docArr[count].srch_links_name+\"</a>\";\r\n");
      out.write("\t\t\t\t\t  newcontent +=\"<span>\"+docArr[count].srch_summary+\"</span><span></span>\";\r\n");
      out.write("\t\t\t\t\t  newcontent +=\"</div>\";\r\n");
      out.write("\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<span class=\\\"countview\\\">\"+usageCount+\" views</span></div>\";\r\n");
      out.write("\t\t\t\t\t\t  }\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t  }else if(isPolicyDoc)\r\n");
      out.write("\t\t\t\t  {\r\n");
      out.write("\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<div>\";\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t \t  newcontent +=\"<div class=\\\"result\\\">\";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<a onmouseover=\\\"document.getElementById('div_name').style.display='';showAddInfo('\"+docArr[count].srch_func+\"', '\"+docArr[count].srch_catg+\"','\"+docArr[count].srch_sub_catg+\"')\\\" \";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"onmouseout=\\\"document.getElementById('div_name').style.display='none';\\\"  \";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  link = String(link);\r\n");
      out.write("                         \tif( link.indexOf('html') !=-1 && link.indexOf('htm') !=-1 && link.indexOf('pdf')!=-1 )\r\n");
      out.write("                            {\r\n");
      out.write("                           \t newcontent +=\"href=\\\"\"+link+\"\\\" onclick=updateUsageCount('\"+id+\"')><img src=\\\"\"+imgSrc+\"\\\" alt=\\\"\"+alt+\"\\\"/> \"+docArr[count].srch_links_name+\"</a>\";\r\n");
      out.write("                            }else\r\n");
      out.write("                            {\r\n");
      out.write("                           \t newcontent +=\"href=\\\"#\\\" onclick=\\\"window.open('\"+link+\"');onclick=updateUsageCount('\"+id+\"')\\\" ><img src=\\\"\"+imgSrc+\"\\\" alt=\\\"\"+alt+\"\\\"/> \"+docArr[count].srch_links_name+\"</a>\";\r\n");
      out.write("                            }\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<span>  \"+docArr[count].srch_summary+\"</span><span></span>\";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"<span class=\\\"countview\\\">\"+usageCount+\" views</span></div>\";\r\n");
      out.write("\t\t\t\t\t\t\t  }\t\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t  else\r\n");
      out.write("\t\t\t\t  {\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<div>\";\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  newcontent +=\"<div class=\\\"result\\\">\";\r\n");
      out.write("\t\t\t\t\t  newcontent +=\"<a onmouseover=\\\"document.getElementById('div_name').style.display='';showAddInfo('\"+docArr[count].srch_func+\"', '\"+docArr[count].srch_catg+\"','\"+docArr[count].srch_sub_catg+\"')\\\" \";\r\n");
      out.write("\t\t\t\t\t  newcontent +=\"onmouseout=\\\"document.getElementById('div_name').style.display='none';\\\"  \";\r\n");
      out.write("\t\t\t\t\t  newcontent  +=\"href=\\\"goSearchResult.htm?id=\"+id+\"&docLink=\"+link+\"&srchTxt=\"+$('#textfield').val().replace(/[^a-zA-Z 0-9]+/g,'')+\"&isTag=\"+isTag+\"\\\" onclick=updateUsageCount('\"+id+\"')><img src=\\\"\"+imgSrc+\"\\\" alt=\\\"\"+alt+\"\\\"/> \"+docArr[count].srch_links_name+\"</a>\";\r\n");
      out.write("\t\t\t\t\t  newcontent +=\"<span >  \"+docArr[count].srch_summary+\"</span>\";\r\n");
      out.write("\t\t\t\t\t  newcontent +=\"</div>\";\r\n");
      out.write("\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<span class=\\\"countview\\\">\"+usageCount+\" views</span></div>\";\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t \t\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\tisTag = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t  $('#Searchresult').html(newcontent);\r\n");
      out.write("       \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t    $(\".result\").dotdotdot({\r\n");
      out.write("\t \t    ellipsis        : '... ',\r\n");
      out.write("\t        wrap            : 'word',\r\n");
      out.write("\t        after           : null,\r\n");
      out.write("\t        watch           : false,\r\n");
      out.write("\t        height          : null,\r\n");
      out.write("\t        tolerance       : 0,\r\n");
      out.write("       callback        : function( isTruncated, orgContent ) {},\r\n");
      out.write("\t        lastCharacter   : {\r\n");
      out.write("\t            remove          : [ ' ', ',', ';', '.', '!', '?' ],\r\n");
      out.write("\t            noEllipsis      : []\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t});\r\n");
      out.write("        }else{\r\n");
      out.write("        \t$(\"#smartSearchImg\").show();\r\n");
      out.write("        \t$(\"#smartSearch\").hide();\r\n");
      out.write("        }\r\n");
      out.write("\t});}\r\n");
      out.write("\t/**\r\n");
      out.write("\tEnd of added by Mohit(816452)/307 to add the Top Ten Viewed Documents onLoad on the screen\r\n");
      out.write("\t**/\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#userRoleId').change(function () {\r\n");
      out.write("    var roleId = $(this).val();\r\n");
      out.write("    var roleName = $(\"#userRoleId option:selected\").text();\r\n");
      out.write("    window.location.href = \"RoleChanged.htm?roleId=\" + roleId + \"&roleName=\" + roleName;\r\n");
      out.write("});\r\n");
      out.write("function invalidateSess(){\r\n");
      out.write("\t  window.location.href='Logout.htm';\r\n");
      out.write("}\r\n");
      out.write("var docArrLength = 0;\r\n");
      out.write("var start =0 ;\r\n");
      out.write("function pageselectCallback(page_index, jq) {\r\n");
      out.write("\tstart = (page_index * 10)+1;\r\n");
      out.write("\tvar newcontent = ' ';\r\n");
      out.write("\tif (docArrLength > 10) {\r\n");
      out.write("\t\tend = (page_index * 10) + 10 ;\r\n");
      out.write("\t\tif(docArrLength > end )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t  $(\"#totalCont\").text(\"Showing \"+start+\" to \"+end+\" of \"+docArrLength+\" results \"  );\r\n");
      out.write("\t\t}else\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t  $(\"#totalCont\").text(\"Showing \"+start+\" to \"+docArrLength+\" of \"+docArrLength+\" results \"  );\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\t $(\"#totalCont\").text(\"Showing \"+start+\" to \"+docArrLength+\" of \"+docArrLength+\" results \"  );\r\n");
      out.write("\t}\r\n");
      out.write("\tif (page_index == 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tstart = 0;\r\n");
      out.write("\t} else\r\n");
      out.write("\t{\r\n");
      out.write("\t\tstart =start -1;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar string =$(\"#textfield\").val().replace(/[^a-zA-Z 0-9]+/g,'');\r\n");
      out.write("\tvar count = string.split(\" \");\r\n");
      out.write("\tif(count.length == 1 || count.length == 2)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tmm =1;\r\n");
      out.write("\t}else\r\n");
      out.write("\t{\r\n");
      out.write("\t\tmm =1;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type: 'GET',\r\n");
      out.write("\t\t\turl :  home+'/select?q='\r\n");
      out.write("\t\t\t+ $(\"#textfield\").val().replace(/[^a-zA-Z 0-9]+/g,'') + '&mm='+mm+'&wt=json&start='+start+'&timSt'+new Date(),\r\n");
      out.write("\t\t  dataType: \"json\",\r\n");
      out.write("\t\t  success: function(xml){\r\n");
      out.write("\t\t  docArrLength = xml.response.numFound;\t\t  \r\n");
      out.write("\t    if(docArrLength == 0)\r\n");
      out.write("\t    {\r\n");
      out.write("\t \t\t  $(\"#Pagination\").hide();\r\n");
      out.write("\t \t\t  $(\"#totalCont\").text(\"No result Found\");\r\n");
      out.write("\t \t\t  $('#Searchresult').html('');\r\n");
      out.write("\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else{\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t  \t\t  var docArr = xml.response.docs;\r\n");
      out.write("\t\t\t  var link = \"\";\r\n");
      out.write("\t\t\t  var id = \"\";\r\n");
      out.write("\t          var isTag = false;\r\n");
      out.write("\t          var isPolicyDoc = false;\r\n");
      out.write("           \t  var imgSrc = \"\";\r\n");
      out.write("              var alt = \"\";\r\n");
      out.write("              var type=\"\";\r\n");
      out.write("              var downloadFileType=\"doc|docx|ppt|pptx|xls|xlsx\"\r\n");
      out.write("              var usageCount=\"\";\r\n");
      out.write("              //Added by Mohit(816452) to get the count for each article\r\n");
      out.write("              if(docArr.length>0){\r\n");
      out.write("            \t  $(\"#smartSearchImg\").hide();\r\n");
      out.write("\t\t\t  for (count = 0; count < docArr.length; count++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tid = docArr[count].id;\r\n");
      out.write("\t\t\t\t\t$.ajaxSetup({async:false});\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t  type: 'GET',\r\n");
      out.write("\t\t\t\t\t\t\turl :'getUsageCount.htm', \r\n");
      out.write("\t\t\t\t\t\t\tdata:{docId:id} ,\r\n");
      out.write("\t\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\tusageCount=data;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t//End of added by Mohit(816452) to get the count for each article\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(docArr[count].id.indexOf('TG') != -1)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tisTag = true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(docArr[count].id.indexOf('DC') != -1)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tlink = docArr[count].srch_links ;\r\n");
      out.write("\t\t\t\t\t\timgSrc=\"images/searchAI/Doc.png\";\r\n");
      out.write("\t\t\t\t\t\talt=\"Document\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(docArr[count].id.indexOf('PD_') != -1)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tisPolicyDoc = true;\r\n");
      out.write("\t\t\t\t\t\tlink = docArr[count].srch_links ;\r\n");
      out.write("\t\t\t\t\t\timgSrc=\"images/searchAI/Doc.png\";\r\n");
      out.write("\t\t\t\t\t\talt=\"Policy Document\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tlink = \"\";\r\n");
      out.write("\t\t\t\t\t\timgSrc=\"images/searchAI/ticket.png\";\r\n");
      out.write("\t\t\t\t\t\talt=\"IConnect Ticket\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t  if(isTag)\r\n");
      out.write("\t\t\t\t\t  {\r\n");
      out.write("\t\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"<div>\";\r\n");
      out.write("\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t \t  newcontent +=\"<div class=\\\"result\\\">\";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<a href=\\\"goSearchResult.htm?id=\"+id+\"&docLink=\"+link+\"&srchTxt=\"+$('#textfield').val().replace(/[^a-zA-Z 0-9]+/g,'')+\"&isTag=\"+isTag+\"\\\" onclick=updateUsageCount('\"+id+\"') \\\"><img src=\\\"images/searchAI/User.png\\\" alt=\\\"User Solution\\\"/> \"+docArr[count].srch_links_name+\"</a>\";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<span>\"+docArr[count].srch_summary+\"</span><span></span>\";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"<span class=\\\"countview\\\">\"+usageCount+\" views</span></div>\";\r\n");
      out.write("\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  }else if(isPolicyDoc)\r\n");
      out.write("\t\t\t\t\t  {\r\n");
      out.write("\t\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"<div>\";\r\n");
      out.write("\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t \t  newcontent +=\"<div class=\\\"result\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"<a onmouseover=\\\"document.getElementById('div_name').style.display='';showAddInfo('\"+docArr[count].srch_func+\"', '\"+docArr[count].srch_catg+\"','\"+docArr[count].srch_sub_catg+\"')\\\" \";\r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"onmouseout=\\\"document.getElementById('div_name').style.display='none';\\\"  \";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  link = String(link);\r\n");
      out.write("                              \tif( link.indexOf('html') !=-1 && link.indexOf('htm') !=-1 && link.indexOf('pdf')!=-1 )\r\n");
      out.write("                                 {\r\n");
      out.write("                                \t newcontent +=\"href=\\\"\"+link+\"\\\" onclick=updateUsageCount('\"+id+\"');\\\"><img src=\\\"\"+imgSrc+\"\\\" alt=\\\"\"+alt+\"\\\"/> \"+docArr[count].srch_links_name+\"</a>\";\r\n");
      out.write("                                 }else\r\n");
      out.write("                                 {\r\n");
      out.write("                                \t newcontent +=\"href=\\\"#\\\" onclick=\\\"window.open('\"+link+\"');onclick=updateUsageCount('\"+id+\"');\\\" ><img src=\\\"\"+imgSrc+\"\\\" alt=\\\"\"+alt+\"\\\"/> \"+docArr[count].srch_links_name+\"</a>\";\r\n");
      out.write("                                 }\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"<span>  \"+docArr[count].srch_summary+\"</span><span></span>\";\r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t\t\t  newcontent +=\"<span class=\\\"countview\\\">\"+usageCount+\" views</span></div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t  }\t\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  else\r\n");
      out.write("\t\t\t\t\t  { \r\n");
      out.write("\t\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"<div>\";\r\n");
      out.write("\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t \t  newcontent +=\"<div class=\\\"result\\\">\";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<a onmouseover=\\\"document.getElementById('div_name').style.display='';showAddInfo('\"+docArr[count].srch_func+\"', '\"+docArr[count].srch_catg+\"','\"+docArr[count].srch_sub_catg+\"')\\\" \";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"onmouseout=\\\"document.getElementById('div_name').style.display='none';\\\"  \";\r\n");
      out.write("\t\t\t\t\t\t newcontent  +=\"href=\\\"goSearchResult.htm?id=\"+id+\"&docLink=\"+link+\"&srchTxt=\"+$('#textfield').val().replace(/[^a-zA-Z 0-9]+/g,'')+\"&isTag=\"+isTag+\"\\\" onclick=updateUsageCount('\"+id+\"')><img src=\\\"\"+imgSrc+\"\\\" alt=\\\"\"+alt+\"\\\"/> \"+docArr[count].srch_links_name+\"</a>\";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"<span>  \"+docArr[count].srch_summary+\"</span>\";\r\n");
      out.write("\t\t\t\t\t\t  newcontent +=\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t  if(usageCount!= 0){\r\n");
      out.write("\t\t\t\t\t\t\t  newcontent +=\"<span class=\\\"countview\\\">\"+usageCount+\" views</span></div>\";\r\n");
      out.write("\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  isTag = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t  $('#Searchresult').html(newcontent);\r\n");
      out.write("\t  \r\n");
      out.write("\t\t\t  $(\"#Pagination\").show();\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t    $(\".result\").dotdotdot({\r\n");
      out.write("\t\t \t    ellipsis        : '... ',\r\n");
      out.write("\t\t        wrap            : 'word',\r\n");
      out.write("\t\t        after           : null,\r\n");
      out.write("\t\t        watch           : false,\r\n");
      out.write("\t\t        height          : null,\r\n");
      out.write("\t\t        tolerance       : 0,\r\n");
      out.write("\t        callback        : function( isTruncated, orgContent ) {},\r\n");
      out.write("\t\t        lastCharacter   : {\r\n");
      out.write("\t\t            remove          : [ ' ', ',', ';', '.', '!', '?' ],\r\n");
      out.write("\t\t            noEllipsis      : []\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    });\r\n");
      out.write("              }else{\r\n");
      out.write("      \t    \t$(\"#smartSearchImg\").show();\r\n");
      out.write("              \t$(\"#smartSearch\").hide();\r\n");
      out.write("      \t    }\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t\t  }   \r\n");
      out.write("\t\t});\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setSubjectFlag(){\r\n");
      out.write("\t$(\"#isSaveSubjectReqd\").val('1');\r\n");
      out.write("}\r\n");
      out.write("function getOptionsFromForm() {\r\n");
      out.write("\tvar opt = {\r\n");
      out.write("\t\tcallback : pageselectCallback\r\n");
      out.write("\t};\r\n");
      out.write("\topt.prev_text = \"Prev\";\r\n");
      out.write("\topt.next_text = \"Next\";\r\n");
      out.write("\t$(\"input:text\")\r\n");
      out.write("\t\t\t.each(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\topt[this.name] = this.className.match(/numeric/) ? parseInt(this.value)\r\n");
      out.write("\t\t\t\t\t\t\t\t: this.value;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\tvar htmlspecialchars ={ \"&\":\"&amp;\", \"<\":\"&lt;\", \">\":\"&gt;\", '\"':\"&quot;\"}\r\n");
      out.write("\t$.each(htmlspecialchars, function(k,v){\r\n");
      out.write("\topt.prev_text = opt.prev_text.replace(k,v);\r\n");
      out.write("\topt.next_text = opt.next_text.replace(k,v);\r\n");
      out.write("\t})\r\n");
      out.write("\treturn opt;\r\n");
      out.write("}\r\n");
      out.write("function showAddInfo(funcName, categ, subCateg ,t)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tvar txt = \r\n");
      out.write("\t\"<ul class=\\\"addInfoContent\\\"><li>Function Name : \"+funcName+\"</li><li>Category : \"+categ+\"</li><li>Sub Category : \"+subCateg+\"</li></ul>\";\r\n");
      out.write("\t$('#div_name').show();\r\n");
      out.write("\t$('#div_name').html(txt);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSubject(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar sub=$('#textfield').val();\r\n");
      out.write("\tif($('#textfield').val() == 'Search Your Query'){\r\n");
      out.write("\t\tsub='';\r\n");
      out.write("\t}\t\r\n");
      out.write("\t//alert(encodeURIComponent(sub));\r\n");
      out.write("\tsub=encodeURIComponent(sub);\r\n");
      out.write("\twindow.location.href=\"UserHome.htm\";\r\n");
      out.write("\treturn false; \r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function setHeaderID(id){\r\n");
      out.write("\t$.session(\"modname1\",id);\r\n");
      out.write("\t$.getJSON('UserHome1.htm',{modname : id},function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\twindow.location.href=\"UserHome.htm\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
 String token = null; 
      out.write("\r\n");
      out.write("<table width=\"102%\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\tcellspacing=\"0\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\" align=\"center\" valign=\"top\" class=\"headerLine\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\tcellspacing=\"0\" class=\"header_bg\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"15%\" align=\"left\" valign=\"middle\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/searchAI/iConnect_Logo.png\" width=\"205\" height=\"60\" /></td>\r\n");
      out.write("\t\t\t\t<td width=\"70%\" align=\"center\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/searchAI/header.png\" /></td>\r\n");
      out.write("\t\t\t\t<td width=\"15%\" align=\"right\" valign=\"middle\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/searchAI/Capgemini_Search_Logo.png\" width=\"130\" height=\"60\"  style=\"margin-right:6px\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" align=\"right\"><span>Welcome <b>");
      out.print(empName );
      out.write("</b>,");
      out.print(location );
      out.write("\r\n");
      out.write("\t\t\t\t</span> <a href=\"login\" class=\"signin\"><img src=\"images/profile.png\"\r\n");
      out.write("\t\t\t\t\talt=\"My Profile\" title=\"My Profile\" /></a> <a\r\n");
      out.write("\t\t\t\t\tonclick=\"iConnectLogOut();\"><img src=\"images/logout.png\"\r\n");
      out.write("\t\t\t\t\talt=\"Logout\" title=\"Logout\" /></a></td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<fieldset id=\"signin_menu\">\r\n");
      out.write("\t\t\t\t<form id=\"changeRole\" action=\"/iconnect/RoleChanged.htm\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\"><select name=\"userRoleId\" id=\"userRoleId\"\r\n");
      out.write("\t\t\t\t\tonchange=\"isChange()\">\r\n");
      out.write("\t\t\t\t\t");

		for(int i = 0; i < userRoleList.size(); i++){
			WORKFLOW_Role role = userRoleList.get(i);
			if(currentUserRole.equalsIgnoreCase(role.getRoleName())){
				currentUserRoleID = role.getRoleId();
		
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print( role.getRoleId());
      out.write("\" selected=\"selected\">");
      out.print( role.getRoleName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");

			}else{
		
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print( role.getRoleId());
      out.write('"');
      out.write('>');
      out.print( role.getRoleName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");

			}
	}
		
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</select></form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"18%\" height=\"69\" align=\"center\" valign=\"top\"\r\n");
      out.write("\t\t\tstyle=\"border-right: 1px dashed #dedede;\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\tcellspacing=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div class=\"board\" id=\"bulletinBoard\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div class=\"helpdesk\">\r\n");
      out.write("\t\t\t\t<div><strong>Helpdesk - IConnect</strong></div>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a onclick=\"setHeaderID('RaiseNewTicket')\" href=\"#\" >Raise\r\n");
      out.write("\t\t\t\t\tNew Ticket</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a onclick=\"setHeaderID('ExistingTickets')\" href=\"#\">View\r\n");
      out.write("\t\t\t\t\tExisting Ticket</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a onclick=\"setHeaderID('WaitingForApproval')\" href=\"#\">Waiting\r\n");
      out.write("\t\t\t\t\tfor My Approval</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a onclick=\"setHeaderID('ApprovedByMe')\" href=\"#\"> Approved\r\n");
      out.write("\t\t\t\t\tBy Me</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a onclick=\"setHeaderID('RejectedByMe')\" href=\"#\">Rejected\r\n");
      out.write("\t\t\t\t\tBy Me</a></li>\r\n");
      out.write("\t\t\t\t<!-- \t<li><a onclick=\"setHeaderID('CreateServiceTicket')\" href=\"#\">Create Service Ticket</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a onclick=\"setHeaderID('ViewServiceTicket')\" href=\"#\">View Service Ticket</a></li> -->\r\n");
      out.write("\t\t\t\t\t<li><a onclick=\"setHeaderID('ContactInfo')\" href=\"#\">Contact\r\n");
      out.write("\t\t\t\t\tInfo</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"62%\" align=\"center\" valign=\"top\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table width=\"98%\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
      out.write("\t\t\tcellspacing=\"0\" >\r\n");
      out.write("<!--Changed by Mohit(816452) for enhancement in UI -->\r\n");
      out.write("<tr>\r\n");
      out.write("\t\t\t\t<td height=\"140\" align=\"center\" valign=\"top\">\r\n");
      out.write("\t\t\t<div id =\"smartSearchImg\" style=\"display:none\"><img src=\"images//searchAI/CominSoonSmartSearch.png\" /></div>\r\n");
      out.write("\t\t\t\t<table width=\"100%\"  border=\"0\" align=\"center\"  id =\"smartSearch\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\tcellspacing=\"0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td height=\"80\" align=\"center\" valign=\"middle\">\r\n");
      out.write("\t\t\t\t\t\t<table cellpadding=\"0\" border=\"0\" cellspacing=\"0\" width=\"700px\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-top: 10px;\" id=\"textfieldContainer\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"65%\" height=\"70px\" class=\"search searchBG1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talign=\"center\"><input name=\"textfield\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"textfield\" value=\"Search Your Query\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonfocus=\"if(this.value == 'Search Your Query') {this.value='';this.style.color='#000';}\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"if(this.value == '') {this.value='Search Your Query';this.style.color='#aaa';}\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"searchBG2\" width=\"21%\" valign=\"top\" align=\"left\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"searchbtn\" type=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images//searchAI/Search_Button.png\" name=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"button\" value=\"Search\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"setSubjectFlag();submitTxt()\" alt=\"Search\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"65%\" id=\"container\" align=\"left\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bulb-img\"><img src=\"images//searchAI/Bulb.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home-tip\">Still raising tickets for common issues?<br/>\r\n");
      out.write("\t\t\t\t\t\t\t\tTry our Smart Search feature with frequently used documents for an instant solution!!\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("<!--End of changed by Mohit(816452) for enhancement in UI -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"left\" valign=\"middle\" class=\"total\"><span\r\n");
      out.write("\t\t\t\t\tid=\"totalCont\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td height=\"102\" align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<div id=\"Searchresult\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"Pagination\" class=\"pagination\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<span class=\"current prev\">Prev</span> <span class=\"current\">1</span>\r\n");
      out.write("\t\t\t\t<a href=\"#\">2</a> <a href=\"#\">3</a> <a href=\"#\">4</a> <a href=\"#\">5</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\">6</a> <a href=\"#\">7</a> <a href=\"#\">8</a> <a href=\"#\">9</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\">10</a> <span>...</span> <a href=\"#\">60</a> <a href=\"#\">61</a>\r\n");
      out.write("\t\t\t\t<a class=\"next\" href=\"#\">Next</a></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"20%\" align=\"left\" valign=\"top\"\r\n");
      out.write("\t\t\tstyle=\"border-left: 1px dashed #dedede;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t");
 token = (String)request.getSession().getAttribute("OWASP_CSRFTOKEN"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"OWASP_CSRFTOKEN\" value=\"");
      out.print( token );
      out.write("\">\r\n");
      out.write("\t\t<div id=\"div_name\"\r\n");
      out.write("\t\t\tstyle=\"display: none; position: absolute; float: right; z-index: 9999; background-color: #FFEBBF; border: 2px solid #e6e6e6; padding: 10px; text-align: left; margin: 0px 50px 0px 10px; width: 200px; vertical-align: middle; margin-top: 10px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div class=\"footer\">Copyright &copy; IGATE. All Rights Reserved.</div>\r\n");
      out.write("<div id=\"outputSaveSol\" style=\"display: none\"></div>\r\n");
      out.write("<div class=\"content\"><input type=\"hidden\" id=\"jbarmessageSaveSol\"\r\n");
      out.write("\tname=\"jbarmessageSaveSol\"></input></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fmethod_005fid_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/view/searchHome.jsp(744,3) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setId("UserComment");
    // /WEB-INF/view/searchHome.jsp(744,3) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setModelAttribute("UserComment");
    // /WEB-INF/view/searchHome.jsp(744,3) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction("saveUserTag.htm");
    // /WEB-INF/view/searchHome.jsp(744,3) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setName("UserComment");
    // /WEB-INF/view/searchHome.jsp(744,3) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("post");
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<table width=\"200\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
          out.write("\t\t\t\tcellspacing=\"0\" id=\"tagTableComingSoon\">\r\n");
          out.write("\t\t\t\t</table>\r\n");
          out.write("\t\t\t<table width=\"200\" border=\"0\" align=\"center\" cellpadding=\"0\"\r\n");
          out.write("\t\t\t\tcellspacing=\"0\" id=\"tagTable\" style=\"display:none\">\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t<div style=\"width: 100%; height: auto; text-align: center;\">\r\n");
          out.write("\t\t\t\t\t<img src=\"images//searchAI/Message.gif\" /></div>\r\n");
          out.write("\t\t\t\t\t<div\r\n");
          out.write("\t\t\t\t\t\tstyle=\"width: 100%; height: auto; margin-top: -16px; text-align: center;\">\r\n");
          out.write("\t\t\t\t\t<img src=\"images//searchAI/Features.png\" /></div>\r\n");
          out.write("\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t</table>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmodelAttribute_005fmethod_005fid_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }
}
