package com.igate.ai.constants;

public class AICONSTANTS {
	public static final String IC_AI_UPDATE_USAGE_COUNT="IF EXISTS" +
			"(select SRCH_ID from IC_AI_SRCH_USAGE_COUNT_DETAILS where SRCH_ID = ?) " +
			"UPDATE IC_AI_SRCH_USAGE_COUNT_DETAILS SET USAGE_COUNT=USAGE_COUNT+1, MODIFIED_BY = ?, MODIFIED_DATE = getdate() " +
			"WHERE SRCH_ID =? " +
			"ELSE " +
			"INSERT INTO IC_AI_SRCH_USAGE_COUNT_DETAILS " +
			"(SRCH_ID,USAGE_COUNT,CREATED_BY,CREATED_DATE) " +
			"VALUES (?,1,?,getdate())";
	
	public static final String IC_AI_GET_TOP_TEN_VIEWED_DOCUMENTS="SELECT top(10) DOC.SRCH_ID AS id," +
			"SRCH_FUNC as srch_func, " +
			"DOC.SRCH_CATG as srch_catg," +
			"DOC.SRCH_SUB_CATG as srch_sub_catg," +
			"DOC.SRCH_DESC AS srch_desc," +
			"DOC.SRCH_TAGS as srch_tags," +
			"DOC.SRCH_TAGS as srch_tags_auto_suggest, " +
			"DOC.SRCH_TAGS as srch_spellDOC,SRCH_LINK as srch_links," +
			"DOC.SRCH_LINK_NAME as srch_links_name," +
			"DOC.SRCH_SUMMARY as srch_summary," +
			"DOC.SRCH_LOC as srch_loc," +
			"isnull(DET.USAGE_COUNT,0) as usage_count " +
			"FROM IC_AI_SRCH_DOCS DOC " +
			"LEFT JOIN IC_AI_SRCH_USAGE_COUNT_DETAILS DET " +
			"on DOC.SRCH_ID = DET.SRCH_ID " +
			"order by usage_count desc";
	
	
	public static final String IC_AI_GET_USAGE_COUNT="select USAGE_COUNT from IC_AI_SRCH_USAGE_COUNT_DETAILS where SRCH_ID like ?";
	
	 //public static final String INSERT_INTO_TICKET_ATTACHMENT_DETAILS="INSERT INTO IC_IHD_TICKET_ATTACHMENT_DETAILS (TICKET_ID,REFERENCE_ID,ATTACHMENT_PATH,ATTACHMENT_NAME,CREATED_BY,CREATED_DATE,IS_CHECKED,IS_ACTIVE) VALUES(?,?,?,?,?,GETDATE(),?,?)";
	 
	 
	 public static final String INSERT_INTO_TICKET_ATTACHMENT_DETAILS="MERGE INTO IC_IHD_TICKET_ATTACHMENT_DETAILS ITHD USING"
		 + " (SELECT ? A_TICKET_ID,? A_REFERENCE_ID,? A_IS_ACTIVE) VAL ON" 
		 + " (ITHD.TICKET_ID=A_TICKET_ID AND ITHD.REFERENCE_ID=A_REFERENCE_ID AND ITHD.IS_ACTIVE=A_IS_ACTIVE)"
		 + " WHEN MATCHED THEN UPDATE SET ATTACHMENT_PATH=?,ATTACHMENT_NAME=?,IS_ACTIVE=1,IS_MAIL_TRIGGERED=?,MODIFIED_BY=?,MODIFIED_DATE=GETDATE()"
		 + " WHEN NOT MATCHED THEN INSERT (TICKET_ID,REFERENCE_ID,ATTACHMENT_PATH,ATTACHMENT_NAME,CREATED_BY,CREATED_DATE,IS_CHECKED,IS_ACTIVE,IS_MAIL_TRIGGERED)"
		 + " VALUES(?,?,?,?,?,GETDATE(),?,?,?);";
	 
	 public static final String UPDATE_INTO_TICKET_ATTACHMENT_DETAILS="UPDATE IC_IHD_TICKET_ATTACHMENT_DETAILS SET IS_ACTIVE=?,MODIFIED_BY=?,MODIFIED_DATE=GETDATE() where TICKET_ID=? and ATTACHMENT_NAME=? and IS_ACTIVE=?";
	 public static final String SELECT_INTO_TICKET_ATTACHMENT_DETAILS="SELECT COUNT(*) 'COUNT' FROM IC_IHD_TICKET_ATTACHMENT_DETAILS where TICKET_ID=? and ATTACHMENT_NAME=? and IS_ACTIVE=?";
	 
	 public static final String CHECK_EXISTS_IN_TICKET_ATTACHMENT_DETAILS="select COUNT(*) 'FLAG' from IC_IHD_TICKET_ATTACHMENT_DETAILS where TICKET_ID=? and REFERENCE_ID=? and IS_ACTIVE=1";
	 

}
